version: "3"

services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Asia/Kolkata
    networks:
      dnsnet:
        ipv4_address: 172.30.12.2
    volumes:
      - ./config:/etc/bind

networks:
  dnsnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
